acme_hello_homepage:
    pattern:  /hello/n/{name}
    defaults: { _controller: AcmeHelloBundle:Default:index }

acme_hello_Test:
    pattern:  /hello/Test
    defaults: { _controller: AcmeHelloBundle:Test:index }
